[clearData ]
[image storage="yellow" layer=black opacity=0]
[image storage="red" layer=black opacity=0]
[image storage="top" layer=background]
[layopt layer=message visible=false]
[ranking ]
[newgame ]
; TODO: cowlickのバージョンをあげたらopacity=255にする
[image storage=black layer=black opacity=1]
[enterScene ]
